spring.application.name=BookManagementSystem

# Database Configuration (H2)
spring.datasource.url=jdbc:h2:mem:BookManagementDB;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# JPA/Hibernate properties
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# JWT Configurations
# Secret key must be at least 256 bits (32 bytes) long
app.jwt.secret=bookManagementSystemSecretKeyMustBeVeryLongToMeetHmacShaRequirements123456
app.jwt.expiration-ms=86400000
